- hosts: localhost

  tasks:
#  - name: Stop existing container if persent with same name
#    command: docker container stop devopsblog
#    ignore_errors: yes

  - name: Delete existing container if persent with same name
    command: docker container rm -f devopsblog
    ignore_errors: yes

  - name: Delete existing image so pull the latest images from dockerhub locally
    command: docker image rmi localhost:5000/devopsblog:v1
    ignore_errors: yes

  - name: Create docker service
    command: docker service create --name devopsblogservice --replicas 1 --publish 11011:8080 localhost:5000/devopsblog:v1
    ignore_errors: yes

  - name: updating existing docker service  
    command: docker service update --force --image localhost:5000/devopsblog:v1 devopsblogservice
    

    
